name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

      - name: Install Dependencies
        run: |
          vcpkg install opencv:x64-windows ffmpeg:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prosense-obs-stitcher-windows
          path: build/Release/prosense-obs-stitcher.exe
